#!/usr/bin/env bash
# scripts/make-bare.sh <dest> - write a copy of this app WITHOUT any Scry hook, to start from when you want the
# "before" state of the how-to (an Android app that Scry knows nothing about). The copy is generated, never committed.
#
# It removes: the debug ScryLaunch.kt / ScryScreens.kt and the release no-op, the hook block in MainActivity.kt
# (between the `scry:begin` and `scry:end` markers), scripts/, docs/screens/, .github/ and the Scry mentions in
# README.md. `./gradlew assembleDebug` in <dest> must build clean.
set -euo pipefail
dest="${1:?usage: scripts/make-bare.sh <dest>}"
src="$(cd "$(dirname "$0")/.." && pwd)"
[ ! -e "$dest" ] || [ -z "$(ls -A "$dest" 2>/dev/null)" ] || { echo "make-bare: $dest exists and is not empty" >&2; exit 1; }
mkdir -p "$dest"

# Copy tracked and unignored files only (no build output, no local.properties, no .scry).
if git -C "$src" rev-parse --git-dir >/dev/null 2>&1; then
  git -C "$src" ls-files -z --cached --others --exclude-standard | (cd "$src" && xargs -0 -I{} cp --parents {} "$dest")
else
  (cd "$src" && tar --exclude=build --exclude=.gradle --exclude=.scry --exclude=local.properties --exclude=.git -cf - .) | tar -xf - -C "$dest"
fi

cd "$dest"
rm -f app/src/debug/java/com/scrymore/kettle/ScryLaunch.kt app/src/debug/java/com/scrymore/kettle/ScryScreens.kt \
      app/src/release/java/com/scrymore/kettle/ScryLaunch.kt
rmdir -p app/src/debug/java/com/scrymore/kettle app/src/release/java/com/scrymore/kettle 2>/dev/null || true
rm -rf scripts docs/screens .github .scry
rmdir docs 2>/dev/null || true

# Replace the hook block with the plain call.
awk '
  /\/\/ scry:begin/ { skipping = 1; print "        setContent { KettleApp() }"; next }
  /\/\/ scry:end/   { skipping = 0; next }
  !skipping         { print }
' app/src/main/java/com/scrymore/kettle/MainActivity.kt > MainActivity.kt.tmp
mv MainActivity.kt.tmp app/src/main/java/com/scrymore/kettle/MainActivity.kt

printf '# Kettle (bare)\n\nThe Kettle sample app with no Scry capture code. Generated by scripts/make-bare.sh in scry-sample-android.\n' > README.md

# Fail loudly if any hook symbol survived.
if grep -rIn --exclude-dir=build --exclude-dir=.gradle -E 'scry_screen|ScryLaunch|ScryScreens|ScryCaptureRoot|SCRY_(API_KEY|PROJECT_ID)' . ; then
  echo "make-bare: hook references left in $dest (listed above)" >&2
  exit 1
fi
echo "make-bare: wrote $dest (build it with: cd $dest && ./gradlew assembleDebug)"
